import java.util.ArrayList; // Import ArrayList class
import java.util.Objects; // Import Objects class

// School class that contains information about school and provides methods to edit school information such as teachers and students
public class School {
    // Fields
    ArrayList<Teacher> teachers; // ArrayList of Teachers
    ArrayList<Student> students; // ArrayList of Students
    String name; // Name of school
    String city; // City school is located in
    int est; // Date school was established

    // Methods
    School(ArrayList<Teacher> teachers, ArrayList<Student> students, String name, String city, int est) { // School constructor
        // Set fields to inputted values
        this.teachers = teachers;
        this.students = students;
        this.name = name;
        this.city = city;
        this.est = est;
    }

    public void addTeacher(Teacher teacher) { // Add a teacher to ArrayList of teachers
        this.teachers.add(teacher);
    }

    public void addStudent(Student student) { // Add a student to ArrayList of students
        this.students.add(student);
    }

    public void deleteTeacher(String firstName, String lastName) { // Delete teacher from ArrayList of teachers
        // Compares inputted first and last names with every teachers' first and last names in ArrayList. If equal, removes said teacher
        this.teachers.removeIf(teacher -> Objects.equals(teacher.getFirstName(), firstName) && Objects.equals(teacher.getLastName(), lastName));
    }

    public void deleteStudent(String firstName, String lastName) { // Delete student from ArrayList of students
        // Compares inputted first and last names with every students' first and last names in ArrayList. If equal, removes said student
        this.students.removeIf(student -> Objects.equals(student.getFirstName(), firstName) && Objects.equals(student.getLastName(), lastName));
    }

    public void showTeachers() { // Show all teachers
        System.out.println("Teachers: "); // Title for teachers
        for (Teacher teacher : this.teachers) { // Iterates over each teacher
            teacher.printTeacher(teacher); // Calls printTeacher from Teacher class, printing out each teacher
        }
        System.out.println(); // Extra space after for readability
    }

    public void showStudents() { // Show all students
        System.out.println("Students: "); // Title for students
        for (Student student : this.students) { // Iterates over each student
            student.printStudent(student); // Calls printStudent from Student class, printing out each student
        }
        System.out.println(); // Extra space after for readability
    }

    // Setters and Getters for name, city, and est (Autogenerated)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public int getEst() {
        return est;
    }

    public void setEst(int est) {
        this.est = est;
    }
}
