// Student class that contains information about each student and provides methods to edit them
public class Student {
    // Fields
    String firstName; // Student's first name
    String lastName; // Student's last name
    int grade; // Student's grade
    int studentNum; // Student's student number
    static int totalNum = 0; // Total number of students

    // Methods
    Student(String firstName, String lastName, int grade) { // Student constructor
        // Set fields to inputted values
        this.firstName = firstName;
        this.lastName= lastName;
        this.grade = grade;
        this.studentNum = totalNum + 100000000; // Creates student number (must be 9 digits) based on number of students
        totalNum += 1; // Increments total number of students
    }

    public void printStudent(Student student) { // Prints student using toString() method
        System.out.println(student.toString());
    }

    // toString Method to return the information of the created student:
    @Override
    public String toString() {
        return "Name: " + this.firstName + " " + this.lastName + " Student Number: " + this.studentNum;
    } // return the student's information following the required format

    // Setters and Getters for all fields except total number (Autogenerated)
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public int getGrade() {
        return grade;
    }

    public void setGrade(int grade) {
        this.grade = grade;
    }

    public int getStudentNum() {
        return studentNum;
    }

    public void setStudentNum(int studentNum) {
        this.studentNum = studentNum;
    }
}
