// Teacher class that contains information about each teacher and provides methods to edit them
public class Teacher {
    // Fields
    String firstName; // Teacher's first name
    String lastName; // Teacher's last name
    String subject; // Teacher's subject

    // Methods
    Teacher(String firstName, String lastName, String subject) { // Teacher constructor
        // Set fields to inputted values
        this.firstName = firstName;
        this.lastName = lastName;
        this.subject = subject;
    }

    public void printTeacher(Teacher teacher) { // Prints teacher using toString() method
        System.out.println(teacher.toString());
    }

    // toString Method to return the information of the created teacher:
    @Override
    public String toString() {
        return "Name: " + this.firstName + " " + this.lastName + " Subject: " + this.subject;
    } // return the teacher's information following the required format

    // Setters and Getters for all fields (Autogenerated)
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
}
